In [ ]:
import pandas as pd
import altair as alt

In [ ]:
prices_df = pd.read_parquet('https://autocpi-public.s3.eu-west-2.amazonaws.com/lrpd/db_prices.parquet')
prices_df.describe()

,quote_date,shop_code,item_id_raw,region,price,item_id
count,4.836896e+07,4.836896e+07,4.836897e+07,4.836896e+07,4.836896e+07,4.836897e+07
mean,2.007762e+05,4.771270e+02,3.880409e+05,6.679112e+00,4.960397e+01,3.883983e+05
std,1.060226e+03,1.531775e+03,1.467557e+05,3.407499e+00,2.058161e+02,1.466723e+05
min,1.988020e+05,1.000000e+00,2.101010e+05,1.000000e+00,1.000000e-02,2.101010e+05
25%,1.998110e+05,3.900000e+01,2.129170e+05,3.000000e+00,1.490000e+00,2.129180e+05
50%,2.008050e+05,8.800000e+01,4.301280e+05,7.000000e+00,4.850000e+00,4.301320e+05
75%,2.017070e+05,8.020000e+02,5.104060e+05,9.000000e+00,1.999000e+01,5.104070e+05
max,2.025100e+05,2.007100e+04,6.404060e+05,1.300000e+01,4.400000e+04,6.404060e+05

In [ ]:
prices_df.describe().round()

       quote_date   shop_code  item_id_raw      region       price     item_id
count  48368958.0  48368958.0   48368973.0  48368958.0  48368958.0  48368973.0
mean     200776.0       477.0     388041.0         7.0        50.0    388398.0
std        1060.0      1532.0     146756.0         3.0       206.0    146672.0
min      198802.0         1.0     210101.0         1.0         0.0    210101.0
25%      199811.0        39.0     212917.0         3.0         1.0    212918.0
50%      200805.0        88.0     430128.0         7.0         5.0    430132.0
75%      201707.0       802.0     510406.0         9.0        20.0    510407.0
max      202510.0     20071.0     640406.0        13.0     44000.0    640406.0

In [ ]:
prices_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48368973 entries, 0 to 48368972
Data columns (total 7 columns):
 #   Column         Dtype
---  ------         -----
 0   quote_date     float64
 1   shop_code      float64
 2   item_id_raw    int32
 3   region         float64
 4   price          float32
 5   indicator_box  object
 6   item_id        int32
dtypes: float32(1), float64(3), int32(2), object(1)
memory usage: 2.0+ GB

In [ ]:
items_df = pd.read_parquet('https://autocpi-public.s3.eu-west-2.amazonaws.com/lrpd/db_item.parquet')

In [ ]:
items_df[items_df['description'].str.contains('loaf', case=False)]

    item_id                     description  date_quote_s  date_quote_e  n_obs
0    210101    LARGE LOAF-WHITE-SLICED-800G        198802        200401  36039
1    210102  LARGE LOAF-WHITE-UNSLICED-800G        198802        202510  56917
2    210105   LARGE WHOLEMEAL LOAF-UNSLICED        198802        200301  27161
4    210107     BROWN LOAF,400G,SLICED-GRAN        198903        200401  29361
7    210110   LARGE WHOLEMEAL LOAF (SLICED)        200302        200401   1506
8    210111  WHITE SLICED LOAF BRANDED 750G        200402        202510  36848
9    210112  BROWN SLICED LOAF BRANDED 400G        200402        200601   2719
10   210113   WHOLEMEAL SLICED LOAF BRANDED        200402        202510  35696

In [ ]:
items_df[items_df['description'].str.contains('milk', case=False)]

,item_id,description,date_quote_s,date_quote_e,n_obs
155,211701,SHOP MILK-PASTEURISED-PER PT,198802,200201,32488
156,211709,SHOP MILK-WHOLE MILK-4PT/2LTR,199002,202510,91066
157,211710,MILK SEMI-PER 2 PINTS/1.136 L,199002,202510,65794
158,211711,MILK-FLAVOURED,199602,200301,11750
159,211712,"MILK, LONG-LIFE, 500ML",200002,200201,3013
160,211713,"MILK FLAVOURED, 180-500MLS/GMS",201402,202510,28711
161,211714,NON-DAIRY MILK DRINK 900ML-1LT,201702,202510,24039
164,211804,POWDERED SKIMMED MILK-198G,198903,200201,24594
171,211812,MILK- FLAVOURED 500-568ML,200302,200601,4253
373,213004,HOT MILK DRINK-300-400G,198802,200601,34269
706,430407,"SMALL SAUCEPAN,MILK",198802,202510,76839

In [ ]:
items_df[items_df['description'].str.contains('butter', case=False)]

     item_id                   description  date_quote_s  date_quote_e  n_obs
127   211301     BUTTER-HOME PRODUCED-250G        198802        201301  47553
128   211302           BUTTER  NEW ZEALAND        199601        199601    192
129   211303                BUTTER  DANISH        199601        199601    185
130   211304          BUTTER-IMPORTED 250G        199602        201301  28928
131   211305             SPREADABLE BUTTER        201302        202510  35311
132   211306          BUTTER 250G SPEC COO        201302        202510  35655
138   211409  PEANUT BUTTER, JAR, 225-350G        201902        202510  18676

In [ ]:
items_df[items_df['description'].str.contains('cereal', case=False)]

    item_id                    description  date_quote_s  date_quote_e  n_obs
19   210208             BREAKFAST CEREAL 4        199601        199601    204
20   210209  BREAKFAST CEREAL 1 NOT MUESLI        199602        200601  20790
21   210210  BREAKFAST CEREAL 2 NOT MUESLI        200002        200601  10196
24   210213             BREAKFAST CEREAL 1        200602        202510  52392
25   210214             BREAKFAST CEREAL 2        200602        202510  52856
26   210215                     CEREAL BAR        201002        202510  41056
27   210216                 HOT OAT CEREAL        201202        202510  37584
30   210219   BREAKFAST CEREAL GLUTEN FREE        202002        202510  12915

In [ ]:
items_df[items_df['description'].str.contains('yoghurt', case=False)]

,item_id,description,date_quote_s,date_quote_e,n_obs
162,211802,YOGHURT-FRUIT-SMALL INDIVIDUAL,198802,199812,26073
166,211806,YOGHURT/FROMAGE FRAIS-SMALL,199902,200901,17264
167,211807,"YOGHURT/FROMAGE 4-6PK, 45-125G",199902,202510,39479
172,211813,PROBIOTIC-STYLE YOGHURT DRINK,200702,201501,19438
173,211814,YOGHURT-SMALL INDIVIDUAL,200902,202510,27211

In [ ]:
items_df[items_df['description'].str.contains('chicken', case=False)]

,item_id,description,date_quote_s,date_quote_e,n_obs
75,210903,FROZEN CHICKEN PIECES,198802,200301,23479
77,210905,FRESH/CHILLED CHICKEN PER KG,198903,202510,105251
78,210906,FRZEN ROASTING CHICKEN PER KG,198903,200601,27761
79,210907,FRESH/CHILLED CHICKEN PIECES,199502,200301,25596
81,210909,FROZEN CHICKEN THIGHS PER KG,200302,200601,2156
82,210910,FRESH BONELESS CHICKEN BREAST,200302,202510,65366
84,210912,FROZEN CHICKEN BREASTS,200602,202001,28902
85,210913,ROTISSERIE CHICKEN [WHOLE],200902,202401,8500
103,211019,FROZ CHICKEN NUGGETS 220-600G,200502,202510,28024
104,211021,CHICKEN KIEV 2 PACK 250-300G,200602,201501,7172
109,211026,CHICKEN KIEV 2 PACK 240-325G,201502,202510,26070
427,220326,TAKEAWAY CHICKEN & CHIPS,201202,202510,19909

In [ ]:
items_df[items_df['description'].str.contains('fish', case=False)]

,item_id,description,date_quote_s,date_quote_e,n_obs
115,211101,FRESH WHITE FISH FILLETS KG,199601,202510,52220
116,211104,FRESH FISH-RAINBOW TROUT-WHOLE,199302,200101,22989
117,211105,FRESH FISH-SALMON FILLETS-KG,200102,202510,39696
119,211202,CANNED FISH-SALMON-200-215G,198802,200201,25688
120,211203,FROZEN FISH FINGERS (10 PACK),198802,200401,32710
121,211204,FROZEN FISH IN SAUCE,198802,200301,29359
122,211207,"CANNED FISH, TUNA, 130G-200G",198903,202510,62490
125,211210,FROZEN FISH FINGERS 8-12 PK,200402,202510,53776
126,211211,FROZEN BREAD/BAT FISH 400-550G,201002,202510,40004
361,212937,CHILLED READY MEAL-FISH/VEG,200902,202510,24690
408,220301,FISH & CHIPS TAKEAWAY,198802,202510,102171
1300,630340,CARBON FIBRE FISHING ROD,200402,202510,22808

In [ ]:
items_df[items_df['description'].str.contains('chocolate', case=False)]

,item_id,description,date_quote_s,date_quote_e,n_obs
45,210322,CHOCOLATE 11,200402,201701,21012
213,212205,INDIVIDUALLY WRAPPED CHOCOLATES,199601,199601,187
214,212207,CANDY COATED CHOCOLATE,198802,201201,42401
215,212208,CHOCOLATE 2,199601,199601,187
216,212209,CHOCOLATE 3,198802,200201,22928
217,212210,CARTON/BOX OF CHOCOLATES 2,199601,199601,199
218,212211,CHOCOLATE 4,198802,202510,68627
219,212212,CHOCOLATE 5,198802,200401,65982
220,212213,CHOCOLATE 6,199601,199601,203
223,212216,CHOCOLATE 7,199601,199601,61
226,212219,CHOCOLATE 8,200202,201801,24559
227,212220,CHOCOLATE COATED PEANUT,200202,200601,4992
228,212221,CHOCOLATE 9,200202,200301,678
229,212222,CHOCOLATE 10,200302,202510,31954
232,212225,CHOCOLATE LARGE BAR 100-200G,201602,202510,23336
233,212226,CHOCOLATE 12,201702,202510,19448
234,212227,CHOCOLATE 13,201802,202101,3880
235,212228,MALTED CHOCOLATE SWEETS,202102,202501,6343
362,212938,CHOCOLATE COVERED ICE CREAM,201202,202510,35231
374,213005,HOT CHOCOLATE DRINK INSTANT,201302,202510,33994

In [ ]:
items_df[items_df['description'].str.contains('banana', case=False)]

     item_id     description  date_quote_s  date_quote_e  n_obs
296   212705  BANANAS-PER LB        198802        199812  39919
309   212719  BANANAS-PER KG        199902        202510  98566

In [ ]:
items_df[items_df['description'].str.contains('biscuit', case=False)]

    item_id                    description  date_quote_s  date_quote_e  n_obs
34   210302        PLAIN BISCUITS-200-300G        198802        202510  70423
35   210304  CHOC COATED BISCUITS-200-300G        198802        200601  35870
46   210323    BISCUITS HALF CHOC 260-400G        201702        202510  23989

In [ ]:
groceries_list = {
    210111: "Bread",
    211709: "Milk",
    211306: "Butter",
    210213: "Cereal",
    210910: "Chicken",
    211101: "Fish",
    212719: "Bananas",
    212211: "Chocolate"
}

In [ ]:
items_df[items_df['item_id'].isin(groceries_list.keys())]

,item_id,description,date_quote_s,date_quote_e,n_obs
8,210111,WHITE SLICED LOAF BRANDED 750G,200402,202510,36848
24,210213,BREAKFAST CEREAL 1,200602,202510,52392
82,210910,FRESH BONELESS CHICKEN BREAST,200302,202510,65366
115,211101,FRESH WHITE FISH FILLETS KG,199601,202510,52220
132,211306,BUTTER 250G SPEC COO,201302,202510,35655
156,211709,SHOP MILK-WHOLE MILK-4PT/2LTR,199002,202510,91066
218,212211,CHOCOLATE 4,198802,202510,68627
309,212719,BANANAS-PER KG,199902,202510,98566

In [ ]:
full_df = pd.merge(prices_df, items_df[['item_id', 'description']], on='item_id')

In [ ]:
full_df['quote_date'] = pd.to_datetime(full_df['quote_date'], format='%Y%m')

In [ ]:
groceries_df = full_df[full_df['item_id'].isin(groceries_list.keys())]

groceries_df

,quote_date,shop_code,item_id_raw,region,price,indicator_box,item_id,description
238753,2015-01-01,98.0,210111,2.0,1.450000,,210111,WHITE SLICED LOAF BRANDED 750G
238754,2006-02-01,89.0,210111,7.0,0.870000,,210111,WHITE SLICED LOAF BRANDED 750G
238755,2009-12-01,814.0,210111,12.0,1.290000,,210111,WHITE SLICED LOAF BRANDED 750G
238756,2008-03-01,808.0,210111,8.0,1.150000,,210111,WHITE SLICED LOAF BRANDED 750G
238757,2010-02-01,814.0,210111,13.0,1.290000,,210111,WHITE SLICED LOAF BRANDED 750G
...,...,...,...,...,...,...,...,...
10930869,2010-12-01,126.0,212719,2.0,0.790000,,212719,BANANAS-PER KG
10930870,1992-04-01,39.0,212719,4.0,0.859802,,212719,BANANAS-PER KG
10930871,1989-07-01,26.0,212719,5.0,1.146402,,212719,BANANAS-PER KG
10930872,1992-12-01,100.0,212719,7.0,0.859802,,212719,BANANAS-PER KG
10930873,1995-05-01,4.0,212719,8.0,1.080264,,212719,BANANAS-PER KG

In [ ]:
shopping_list = groceries_df.groupby(['quote_date', 'description', 'item_id']).agg({'price': 'mean'}).reset_index()

shopping_list

     quote_date                     description  item_id      price
0    1988-02-01                  BANANAS-PER KG   212719   1.076573
1    1988-02-01                     CHOCOLATE 4   212211   0.197080
2    1988-03-01                  BANANAS-PER KG   212719   1.061639
3    1988-03-01                     CHOCOLATE 4   212211   0.199340
4    1988-04-01                  BANANAS-PER KG   212719   1.055542
...         ...                             ...      ...        ...
2607 2025-10-01                     CHOCOLATE 4   212211   1.044912
2608 2025-10-01   FRESH BONELESS CHICKEN BREAST   210910   9.713170
2609 2025-10-01     FRESH WHITE FISH FILLETS KG   211101  22.262733
2610 2025-10-01   SHOP MILK-WHOLE MILK-4PT/2LTR   211709   1.803522
2611 2025-10-01  WHITE SLICED LOAF BRANDED 750G   210111   1.325385

[2612 rows x 4 columns]

In [ ]:
complete_dates = shopping_list.groupby('quote_date').filter(lambda x: set(groceries_list.keys()).issubset(set(x['item_id'])))

earliest_complete_date = complete_dates['quote_date'].min()

last_complete_date = complete_dates['quote_date'].max()

In [ ]:
shopping_list = shopping_list[(shopping_list['quote_date'] >= earliest_complete_date) & (shopping_list['quote_date'] <= last_complete_date)]

In [ ]:
shopping_list['item_name'] = shopping_list['item_id'].map(groceries_list)

shopping_list

/tmp/ipykernel_517/4208791875.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shopping_list['item_name'] = shopping_list['item_id'].map(groceries_list)

     quote_date                     description  item_id      price  item_name
1388 2013-02-01                  BANANAS-PER KG   212719   1.054737    Bananas
1389 2013-02-01              BREAKFAST CEREAL 1   210213   2.186966     Cereal
1390 2013-02-01            BUTTER 250G SPEC COO   211306   1.491762     Butter
1391 2013-02-01                     CHOCOLATE 4   212211   0.625611  Chocolate
1392 2013-02-01   FRESH BONELESS CHICKEN BREAST   210910   9.524565    Chicken
...         ...                             ...      ...        ...        ...
2607 2025-10-01                     CHOCOLATE 4   212211   1.044912  Chocolate
2608 2025-10-01   FRESH BONELESS CHICKEN BREAST   210910   9.713170    Chicken
2609 2025-10-01     FRESH WHITE FISH FILLETS KG   211101  22.262733       Fish
2610 2025-10-01   SHOP MILK-WHOLE MILK-4PT/2LTR   211709   1.803522       Milk
2611 2025-10-01  WHITE SLICED LOAF BRANDED 750G   210111   1.325385      Bread

[1224 rows x 5 columns]

In [ ]:
shopping_list.to_csv('shopping_list.csv', index=False)