In [1]:
from ecostyles import EcoStyles
# Create styles instance
styles = EcoStyles()

import altair as alt
import pandas as pd

In [2]:
# Register and enable a theme
styles.register_and_enable_theme(theme_name="article")

In [3]:
# Load Excel file as df
wc_df = pd.read_excel('wc2026-probs.xlsx')

# Reset column index
wc_df = wc_df.rename(columns={'Unnamed: 0': 'id'}).set_index('id')

# Rename to capitalize country names
wc_df['team'] = wc_df['team'].str.title()

# Fill NaN probability values with 0
prob_cols = ['p.l32', 'p.l16', 'p.qf', 'p.sf', 'p.f', 'p.w']
wc_df[prob_cols] = wc_df[prob_cols].fillna(0)

wc_df

,team,FreqL32,FreqL16,FreqQF,FreqSF,FreqFinal,FreqWinners,p.l32,p.l16,p.qf,p.sf,p.f,p.w,team1_id,elorating1,att_strength,def_strength,primary,secondary
id,,,,,,,,,,,,,,,,,,,
12,Curacao,848,67,1,NaN,NaN,NaN,8.48,0.67,0.01,0.00,0.00,0.00,5471,991.490326,0.521416,4.031103,#003DA5,#F9A12E
21,Haiti,856,79,10,NaN,NaN,NaN,8.56,0.79,0.10,0.00,0.00,0.00,3172,1028.238958,0.545791,2.953323,#00209F,#D21034
20,Ghana,3656,506,81,6.0,NaN,NaN,36.56,5.06,0.81,0.06,0.00,0.00,3116,1033.113994,0.932840,2.664758,#006B3F,#FCD116
6,Bosnia-Hz.,4881,1269,141,12.0,NaN,NaN,48.81,12.69,1.41,0.12,0.00,0.00,2984,1060.300489,0.671575,2.676698,#1E3A5F,#FFCC00
30,New Zealand,2468,652,82,9.0,NaN,NaN,24.68,6.52,0.82,0.09,0.00,0.00,1897,1072.169807,0.757924,2.385003,#CCCCCC,#000000
9,Cape Verde Is.,3057,567,153,21.0,1.0,1.0,30.57,5.67,1.53,0.21,0.01,0.01,3925,1080.421469,0.778475,0.909406,#003893,#CF2027
39,South Africa,4359,1374,274,43.0,2.0,NaN,43.59,13.74,2.74,0.43,0.02,0.00,351,1080.517678,0.773706,1.860480,#007A4D,#FFB612
35,Qatar,2689,417,53,2.0,NaN,NaN,26.89,4.17,0.53,0.02,0.00,0.00,3124,1082.162211,0.943369,2.857189,#8B1A1A,#CCCCCC
26,Jordan,1182,136,24,NaN,NaN,NaN,11.82,1.36,0.24,0.00,0.00,0.00,3180,1088.794191,0.973156,2.411047,#007A3D,#CE1126
36,Saudi Arabia,1465,266,32,2.0,NaN,NaN,14.65,2.66,0.32,0.02,0.00,0.00,2226,1091.988902,0.629813,2.675689,#006C35,#CCCCCC
23,Iraq,1391,239,53,8.0,NaN,NaN,13.91,2.39,0.53,0.08,0.00,0.00,3181,1115.838886,0.790692,2.212244,#CE1126,#007A3D
14,Dr Congo,4923,1442,461,120.0,11.0,7.0,49.23,14.42,4.61,1.20,0.11,0.07,3118,1116.806784,0.736187,1.191732,#007FFF,#F7D11E
44,Tunisia,5035,1258,449,129.0,16.0,5.0,50.35,12.58,4.49,1.29,0.16,0.05,2015,1135.115652,0.965039,1.121092,#E70013,#CCCCCC
37,Scotland,7107,2555,878,224.0,17.0,6.0,71.07,25.55,8.78,2.24,0.17,0.06,2264,1150.126923,1.192175,1.590042,#003366,#CCCCCC
13,Czech Rep,7848,3516,958,226.0,14.0,7.0,78.48,35.16,9.58,2.26,0.14,0.07,716,1161.641823,1.216254,1.451305,#D7141A,#CCCCCC
32,Panama,2619,431,91,15.0,NaN,NaN,26.19,4.31,0.91,0.15,0.00,0.00,3267,1179.435552,1.017915,1.991482,#D21034,#CCCCCC
48,Uzbekistan,3831,1192,354,85.0,5.0,2.0,38.31,11.92,3.54,0.85,0.05,0.02,3268,1181.593355,0.806547,0.883019,#1EB53A,#CCCCCC
42,Sweden,4932,1310,500,148.0,10.0,6.0,49.32,13.10,5.00,1.48,0.10,0.06,2517,1188.170325,1.544819,1.757565,#006AA7,#FECC00
16,Egypt,7448,3485,1040,280.0,38.0,21.0,74.48,34.85,10.40,2.80,0.38,0.21,886,1192.627116,0.923880,1.384648,#C8102E,#CCCCCC
24,Ivory Coast,7295,2687,738,172.0,14.0,10.0,72.95,26.87,7.38,1.72,0.14,0.10,3115,1193.391472,1.036006,1.000339,#F77F00,#009A44
31,Norway,8897,4674,2015,927.0,176.0,112.0,88.97,46.74,20.15,9.27,1.76,1.12,1896,1198.365906,1.798315,0.942461,#EF2B2D,#CCCCCC
4,Austria,9080,3808,1843,789.0,178.0,120.0,90.80,38.08,18.43,7.89,1.78,1.20,165,1209.259087,1.600351,1.032949,#ED2939,#CCCCCC
1,Algeria,7176,3121,1193,389.0,62.0,37.0,71.76,31.21,11.93,3.89,0.62,0.37,67,1209.409440,1.408471,1.522226,#006233,#CCCCCC
3,Australia,6197,2954,1054,281.0,25.0,15.0,61.97,29.54,10.54,2.81,0.25,0.15,152,1215.937177,1.402556,1.070202,#FFD700,#00843D
33,Paraguay,6531,3100,1090,312.0,39.0,25.0,65.31,31.00,10.90,3.12,0.39,0.25,2008,1219.112859,0.955121,0.672755,#D52B1E,#CCCCCC
40,South Korea,6771,2727,752,218.0,8.0,4.0,67.71,27.27,7.52,2.18,0.08,0.04,717,1230.392442,1.048952,1.673281,#C60C30,#CCCCCC
45,Turkey,6861,2904,894,242.0,31.0,16.0,68.61,29.04,8.94,2.42,0.31,0.16,2572,1233.617623,1.166847,1.306145,#E30A17,#CCCCCC
8,Canada,9018,4506,1360,354.0,38.0,26.0,90.18,45.06,13.60,3.54,0.38,0.26,506,1236.389120,0.892667,1.098864,#FF0000,#CCCCCC
38,Senegal,7501,3703,1792,720.0,115.0,79.0,75.01,37.03,17.92,7.20,1.15,0.79,3121,1241.383726,1.321201,0.752250,#00853F,#FDEF42
22,Iran,8017,4233,1523,464.0,64.0,37.0,80.17,42.33,15.23,4.64,0.64,0.37,1377,1242.666425,1.317737,1.124133,#239F40,#CCCCCC
47,Usa,7819,3970,1454,340.0,35.0,23.0,78.19,39.70,14.54,3.40,0.35,0.23,2652,1258.297922,1.375119,1.338461,#002868,#BF0A30
43,Switzerland,9649,6094,2310,1120.0,245.0,161.0,96.49,60.94,23.10,11.20,2.45,1.61,2527,1277.063571,1.901212,1.251970,#D52B1E,#CCCCCC
5,Belgium,9376,6381,3414,1435.0,370.0,251.0,93.76,63.81,34.14,14.35,3.70,2.51,275,1277.718439,1.450152,0.649293,#000000,#EF3340
15,Ecuador,9137,5040,2239,1015.0,200.0,117.0,91.37,50.40,22.39,10.15,2.00,1.17,868,1288.654645,1.022195,0.528421,#FFD100,#034EA2
28,Morocco,9200,5186,3005,1419.0,286.0,172.0,92.00,51.86,30.05,14.19,2.86,1.72,1747,1295.958214,1.052774,0.540578,#C1272D,#006233
27,Mexico,8286,4533,1692,413.0,42.0,30.0,82.86,45.33,16.92,4.13,0.42,0.30,1788,1299.778380,1.093889,0.880921,#006847,#CCCCCC
11,Croatia,9527,5210,2769,1361.0,312.0,225.0,95.27,52.10,27.69,13.61,3.12,2.25,670,1302.564354,1.465646,0.525301,#FF0000,#CCCCCC
25,Japan,8277,4089,2480,1156.0,208.0,149.0,82.77,40.89,24.80,11.56,2.08,1.49,1392,1304.453409,1.673133,0.899663,#BC002D,#CCCCCC
46,Uruguay,9586,4039,2354,1367.0,285.0,191.0,95.86,40.39,23.54,13.67,2.85,1.91,2651,1316.843579,1.515489,0.454499,#5CB8E5,#CCCCCC
19,Germany,9843,6283,3055,1561.0,263.0,185.0,98.43,62.83,30.55,15.61,2.63,1.85,1084,1318.926861,2.053814,0.960556,#CCCCCC,#000000
29,Netherlands,8817,4812,3244,1724.0,427.0,346.0,88.17,48.12,32.44,17.24,4.27,3.46,1843,1343.762677,2.163207,0.748481,#FF6600,#CCCCCC
7,Brazil,9820,6225,4203,2305.0,597.0,463.0,98.20,62.25,42.03,23.05,5.97,4.63,395,1360.442066,2.110398,0.620124,#FFD700,#009C3B
10,Colombia,8438,5250,3263,1842.0,645.0,502.0,84.38,52.50,32.63,18.42,6.45,5.02,613,1367.934725,1.778892,0.604550,#FCD116,#003087
34,Portugal,9286,6402,4520,2608.0,1133.0,865.0,92.86,64.02,45.20,26.08,11.33,8.65,2082,1372.070938,2.156463,0.694231,#006600,#CC0000
17,England,9792,6617,4216,2911.0,1032.0,842.0,97.92,66.17,42.16,29.11,10.32,8.42,909,1377.749358,1.362881,0.518161,#CCCCCC,#CC0000
41,Spain,9910,6199,4756,3286.0,1647.0,1395.0,99.10,61.99,47.56,32.86,16.47,13.95,2428,1434.281496,2.110057,0.507703,#AA151B,#F1BF00
18,France,9488,7238,5121,3527.0,1485.0,1216.0,94.88,72.38,51.21,35.27,14.85,12.16,1040,1460.280007,1.650765,0.297852,#002395,#ED2939
2,Argentina,9810,7254,6016,4412.0,2670.0,2331.0,98.10,72.54,60.16,44.12,26.70,23.31,128,1474.526137,1.928752,0.237721,#74ACDF,#CCCCCC

In [4]:
# Create top 15 for bar chart
top15_df = wc_df.nlargest(15, 'p.w').reset_index()
top15_df

,id,team,FreqL32,FreqL16,FreqQF,FreqSF,FreqFinal,FreqWinners,p.l32,p.l16,p.qf,p.sf,p.f,p.w,team1_id,elorating1,att_strength,def_strength,primary,secondary
0,2,Argentina,9810,7254,6016,4412.0,2670.0,2331.0,98.10,72.54,60.16,44.12,26.70,23.31,128,1474.526137,1.928752,0.237721,#74ACDF,#CCCCCC
1,41,Spain,9910,6199,4756,3286.0,1647.0,1395.0,99.10,61.99,47.56,32.86,16.47,13.95,2428,1434.281496,2.110057,0.507703,#AA151B,#F1BF00
2,18,France,9488,7238,5121,3527.0,1485.0,1216.0,94.88,72.38,51.21,35.27,14.85,12.16,1040,1460.280007,1.650765,0.297852,#002395,#ED2939
3,34,Portugal,9286,6402,4520,2608.0,1133.0,865.0,92.86,64.02,45.20,26.08,11.33,8.65,2082,1372.070938,2.156463,0.694231,#006600,#CC0000
4,17,England,9792,6617,4216,2911.0,1032.0,842.0,97.92,66.17,42.16,29.11,10.32,8.42,909,1377.749358,1.362881,0.518161,#CCCCCC,#CC0000
5,10,Colombia,8438,5250,3263,1842.0,645.0,502.0,84.38,52.50,32.63,18.42,6.45,5.02,613,1367.934725,1.778892,0.604550,#FCD116,#003087
6,7,Brazil,9820,6225,4203,2305.0,597.0,463.0,98.20,62.25,42.03,23.05,5.97,4.63,395,1360.442066,2.110398,0.620124,#FFD700,#009C3B
7,29,Netherlands,8817,4812,3244,1724.0,427.0,346.0,88.17,48.12,32.44,17.24,4.27,3.46,1843,1343.762677,2.163207,0.748481,#FF6600,#CCCCCC
8,5,Belgium,9376,6381,3414,1435.0,370.0,251.0,93.76,63.81,34.14,14.35,3.70,2.51,275,1277.718439,1.450152,0.649293,#000000,#EF3340
9,11,Croatia,9527,5210,2769,1361.0,312.0,225.0,95.27,52.10,27.69,13.61,3.12,2.25,670,1302.564354,1.465646,0.525301,#FF0000,#CCCCCC
10,46,Uruguay,9586,4039,2354,1367.0,285.0,191.0,95.86,40.39,23.54,13.67,2.85,1.91,2651,1316.843579,1.515489,0.454499,#5CB8E5,#CCCCCC
11,19,Germany,9843,6283,3055,1561.0,263.0,185.0,98.43,62.83,30.55,15.61,2.63,1.85,1084,1318.926861,2.053814,0.960556,#CCCCCC,#000000
12,28,Morocco,9200,5186,3005,1419.0,286.0,172.0,92.00,51.86,30.05,14.19,2.86,1.72,1747,1295.958214,1.052774,0.540578,#C1272D,#006233
13,43,Switzerland,9649,6094,2310,1120.0,245.0,161.0,96.49,60.94,23.10,11.20,2.45,1.61,2527,1277.063571,1.901212,1.251970,#D52B1E,#CCCCCC
14,25,Japan,8277,4089,2480,1156.0,208.0,149.0,82.77,40.89,24.80,11.56,2.08,1.49,1392,1304.453409,1.673133,0.899663,#BC002D,#CCCCCC

In [5]:
# Create top 10 for slope chart
top10_df = wc_df.nlargest(10, 'p.w').reset_index()

# Specify stage order
stage_order = ['p.l32', 'p.l16', 'p.qf', 'p.sf', 'p.f', 'p.w']

# Melt top 10 into long format for charting
slope_long = top10_df.melt(
    id_vars=['team'],
    value_vars=stage_order,
    var_name='stage',
    value_name='probability'
)

# Make stage ordered for correct x-axis sequence
slope_long['stage'] = pd.Categorical(slope_long['stage'], categories=stage_order, ordered=True)

In [7]:
# Create winner probability bar chart
win_bar = alt.Chart(top15_df).mark_bar().encode(
    x = alt.X(
        'p.w:Q',
        title='Probability of winning (%)',
        axis=alt.Axis(grid=False)),
    y = alt.Y(
        'team:N',
        sort=alt.EncodingSortField(field='p.w', op='sum', order='descending'),
        title=''),
    tooltip = [
        alt.Tooltip('team:N', title='Team'),
        alt.Tooltip('p.w:Q', title='Win probability (%)', format='.2f')
    ]
)
win_bar

alt.Chart(...)